name: Unit

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8, 11, 17, 21 ]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout Java Client
        uses: actions/checkout@v3

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Unit Test
        if: ${{ matrix.java != 8 }}
        run: ./gradlew clean unitTest

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        if: ${{ matrix.java == 8 }}
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Unit Test
        if: ${{ matrix.java == 8 }}
        run: ./gradlew clean unitTest -D"runtime.java=8"
